version: "3.9"
services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- -p 3000 -H 0.0.0.0"

